@extends('layouts.app')

@section('content')
<main class="space-y-6">
    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
            <div><a href="{{ route('cash-officer.gl-payment-reviews') }}" class="text-sm text-slate-500 hover:text-[#234E70]">&larr; Back to Cash Review Batches</a><p class="mt-4 text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Cash Officer Batch Workspace</p><h1 class="mt-2 text-3xl font-black text-sky-950">{{ $batch->batch_no }}</h1><p class="mt-2 text-sm text-slate-500">Review each included GL record one by one. Once all records are reviewed, the batch will move to the cash approver.</p></div>
            @if($batch->ors_number || $batch->dv_number || $batch->lddap_ada_number)<div class="flex flex-wrap gap-3">@if($batch->ors_number)<a href="{{ route('gl-finance-batches.documents.ors', $batch->id, false) }}" target="_blank" rel="noopener noreferrer" class="inline-flex items-center rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100">View ORS</a>@endif @if($batch->dv_number)<a href="{{ route('gl-finance-batches.documents.dv', $batch->id, false) }}" target="_blank" rel="noopener noreferrer" class="inline-flex items-center rounded-xl bg-[#234E70] px-4 py-2 text-sm font-semibold text-white hover:bg-[#18384f]">View DV</a>@endif @if($batch->lddap_ada_number)<a href="{{ route('gl-finance-batches.documents.lddap-ada', $batch->id, false) }}" target="_blank" rel="noopener noreferrer" class="inline-flex items-center rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100">View LDDAP-ADA</a>@endif</div>@endif
        </div>
    </section>
    <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-[0.16em] text-slate-500">Payment Status</p><div class="mt-3"><span class="inline-flex rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-[11px] font-black uppercase tracking-[0.16em] text-blue-700">{{ $batch->status === 'for_compliance_cash_officer' ? 'For Compliance (Cash Officer)' : 'For Processing (Cash)' }}</span></div></article><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-[0.16em] text-slate-500">Included Records</p><p class="mt-3 text-lg font-black text-slate-900">{{ $batch->application_count }}</p></article><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-[0.16em] text-slate-500">Fund Source</p><p class="mt-3 text-lg font-black text-slate-900">{{ $batch->finance_fund_source_name ?? '-' }}</p></article><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-[0.16em] text-slate-500">Batch Total</p><p class="mt-3 text-lg font-black text-slate-900">PHP {{ number_format((float) $batch->total_amount, 2) }}</p></article></section>
    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between gap-3"><div><h2 class="text-xl font-black text-sky-950">Included GL Records</h2><p class="mt-1 text-sm text-slate-500">Open each record below to submit the one-by-one cash review.</p></div></div><div class="mt-5 overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr class="text-left text-xs font-bold uppercase tracking-[0.16em] text-slate-500"><th class="px-4 py-3">#</th><th class="px-4 py-3">Reference</th><th class="px-4 py-3">Client</th><th class="px-4 py-3">Review Status</th><th class="px-4 py-3">Utilized Amount</th><th class="px-4 py-3">Action</th></tr></thead><tbody class="divide-y divide-slate-200 bg-white">@foreach($batch->applications as $application)<tr><td class="px-4 py-4 align-top font-semibold text-slate-900">{{ $application->pivot->sequence_no }}</td><td class="px-4 py-4 align-top"><p class="font-semibold text-slate-900">{{ $application->reference_no }}</p><p class="mt-1 text-xs text-slate-500">{{ $application->assistanceDetail?->name ?? ($application->assistanceType?->name ?? 'GL Case') }}</p></td><td class="px-4 py-4 align-top">{{ trim(($application->client?->first_name ?? '').' '.($application->client?->last_name ?? '')) ?: '-' }}</td><td class="px-4 py-4 align-top text-sm text-slate-700">{{ $application->gl_cash_reviewed_at ? 'Reviewed' : 'Pending Review' }}</td><td class="px-4 py-4 align-top font-semibold text-slate-900">PHP {{ number_format((float) $application->pivot->utilized_amount, 2) }}</td><td class="px-4 py-4 align-top"><a href="{{ route('cash-officer.gl-payment-reviews.records.show', [$batch->id, $application->id]) }}" class="inline-flex items-center rounded-xl bg-[#234E70] px-3 py-2 text-xs font-semibold text-white hover:bg-[#18384f]">{{ $application->gl_cash_reviewed_at ? 'View Record' : 'Review Record' }}</a></td></tr>@endforeach</tbody></table></div></section>
</main>
@endsection
