import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#566676",
        "on-primary-fixed-variant": "#154b6d",
        "secondary-fixed": "#d3e4f7",
        "on-secondary-fixed": "#0c1d2a",
        "primary-fixed-dim": "#9dcbf4",
        "secondary-fixed-dim": "#b7c8da",
        "primary-fixed": "#cce5ff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#f1be76",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9fb",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#384857",
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#d3e4f7",
        "on-background": "#191c1e",
        "outline-variant": "#c1c7cf",
        "on-primary-fixed": "#001e31",
        "outline": "#72787f",
        "surface-tint": "#326286",
        "primary-container": "#1b4f72",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#e4b36c",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface-container": "#eceef0",
        "primary": "#003857",
        "on-primary-container": "#92c0e9",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#291800",
        "inverse-primary": "#9dcbf4",
        "tertiary-fixed": "#ffddb2",
        "tertiary-container": "#674404",
        "surface-container-highest": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "surface": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9fb",
        "secondary": "#506070",
        "on-surface-variant": "#41474e",
        "on-tertiary-fixed-variant": "#624000",
        "on-primary": "#ffffff",
        "tertiary": "#4a2f00"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Public Sans"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
}